@url = http://localhost 
@port = 3000 
### 
GET {{url}}:{{port}}
### 
 GET {{url}}:{{port}}/company/detail
### 
 DELETE {{url}}:{{port}}/category/6
### 
 POST {{url}}:{{port}}/recipe Content-Type: application/x-www-form-urlencoded